config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :banner_sets do
      resources :banners, :only => [:new, :create]
    end
    resources :banners, :only => [:show, :edit, :update, :destroy] do
      put :sort, :on => :collection
    end
  end

end

app/controllers/admin/banners_controller.rb
class Admin::BannersController < Admin::ApplicationController

  before_action :load_set, only: [:new, :create]
  before_action :load_record, only: [:edit, :update, :destroy]
  respond_to :html
  layout false

  def new
    @banner = @banner_set.banners.new(start_date: Time.zone.today)
    respond_with @banner
  end

  def create
    @banner = @banner_set.banners.build
    @banner.attributes = banner_params

    last_banner = SpudBanner.select(:sort_order)
                            .where(spud_banner_set_id: @banner_set.id)
                            .order(sort_order: :desc).first
    @banner.sort_order = last_banner.sort_order + 1 if last_banner

    if @banner.save
      flash.now[:notice] = 'Banner created successfully'
      render 'show'
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    respond_with @banner
  end

  def update
    if @banner.update(banner_params)
      flash.now[:notice] = 'Banner created successfully'
      render 'show'
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @banner.destroy
    head :ok
  end

  # rubocop:disable Rails/SkipsModelValidations
  def sort
    banner_ids = params[:spud_banner_ids]
    banners = SpudBanner.where(id: banner_ids).to_a
    SpudBanner.transaction do
      banner_ids.each_with_index do |id, index|
        banner = banners.select { |b| b.id == id.to_i }.first
        banner.update_column(:sort_order, index)
      end
      banners.last.owner.touch
    end
    head :ok
  end
  # rubocop:enable Rails/SkipsModelValidations

  private

  def load_set
    @banner_set = SpudBannerSet.find_by!(id: params[:banner_set_id])
  end

  def load_record
    @banner = SpudBanner.find_by!(id: params[:id])
  end

  def banner_params
    params.require(:spud_banner).permit(
      :banner, :link_to, :link_target, :title, :alt, :sort_order, :rich_text, :start_date, :end_date
    )
  end

end

app/helpers/admin/banners_helper.rb
module Admin::BannersHelper
end

app/views/admin/banners/_banner.html.erb
<%= content_tag :tr, 'data-id' => banner.id, :class => 'admin-banner-set-item' do %>
  <td>
    <span class="glyphicon glyphicon-sort" aria-hidden="true"></span>
  </td>
  <td width="200">
    <%= link_to banner.banner.url(:banner), :target => :blank do %>
      <%= image_tag banner.banner.url(:tiny) %>
    <% end %>
  </td>
  <td><%= banner.start_date.try(:strftime, '%m/%d/%Y') %></td>
  <td class="table-actions">
    <%= banner.end_date.try(:strftime, '%m/%d/%Y') %>
    <% if banner.expired? %>
      <span class="label">Expired</span>
    <% end %>
  </td>
  <% if !banner.owner.has_rich_text %>
    <td>
      <% if banner.link_to.present? %>
        <%= link_to banner.link_to, banner.link_to, :target => :blank %>
      <% else %>
        n/a
      <% end %>
    </td>
  <% end %>
  <td class="table-actions">
    <%= link_to 'Edit', edit_admin_banner_path(banner), :class => 'admin-banner-set-item-edit btn btn-sm btn-default' %>
    <%= link_to 'Delete', admin_banner_path(banner), :class => 'admin-banner-set-item-delete btn btn-sm btn-danger' %>
  </td>
<% end %>

app/views/admin/banners/_form.html.erb
<%= form_for @banner, :url => path, :builder => TbCore::FormBuilder, :html => { :class => 'admin-banner-form' } do |f| %>

  <%= tb_form_errors(f.object) %>

    <div class="form-group">
      <%= f.label :banner, 'Banner', :class => 'control-label' %>
      <div class="controls">
        <%= f.file_field :banner %>
      </div>
    </div>
    <% if @banner.owner.has_rich_text? %>
       <div class="form-group">
        <%= f.label :rich_text, 'Rich Text', :class => 'control-label' %>
        <div class="controls">
          <%= f.text_area :rich_text, :id => 'admin-banner-rich-text', :class => 'admin-banner-rich-text' %>
        </div>
      </div>
    <% else %>
      <div class="form-group">
        <%= f.label :link_to, 'Link to', :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :link_to %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :link_target, 'Open Link in', :class => 'control-label' %>
        <div class="controls">
          <%= f.select :link_target, options_for_select([
            ['Same Window', '_self'],
            ['New Window', '_blank']
          ], @banner.link_target) %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :title, 'Image Title', :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :title %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :alt, 'Alt Text', :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :alt %>
        </div>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :start_date, 'Start Date', :class => 'control-label' %>
      <div class="controls controls-banner-date-selects">
        <%= f.date_select :start_date, :start_year => Time.zone.today.year %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :end_date, 'End Date', :class => 'control-label' %>
      <div class="controls controls-banner-date-selects">
        <%= f.date_select :end_date, :include_blank => true, :start_year => Time.zone.today.year %>
        <span class="help-block">Leave blank to never expire</span>
      </div>
    </div>

  <div class="progress progress-striped active admin-banner-upload-progress">
    <div class="bar"></div>
  </div>

<% end %>

app/views/admin/banners/edit.html.erb
<%= render :partial => 'form', :locals => {:path => admin_banner_path(@banner)} %>

app/views/admin/banners/new.html.erb
<%= render :partial => 'form', :locals => {:path => admin_banner_set_banners_path(@banner_set)} %>

app/views/admin/banners/show.html.erb
<%= render :partial => 'banner', :locals => {:banner => @banner} %>