config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :banner_sets do
      resources :banners, :only => [:new, :create]
    end
    resources :banners, :only => [:show, :edit, :update, :destroy] do
      put :sort, :on => :collection
    end
  end

end

app/controllers/admin/banner_sets_controller.rb
class Admin::BannerSetsController < Admin::ApplicationController

  before_action :load_record, only: [:show, :edit, :update, :destroy]
  respond_to :html
  belongs_to_app :banner_sets
  add_breadcrumb 'Banner Sets', :admin_banner_sets_path
  layout false

  def index
    @banner_sets = SpudBannerSet.all
    respond_with @banner_sets, layout: 'admin/detail'
  end

  def show
    respond_with @banner_set, layout: 'admin/detail'
  end

  def new
    @banner_set = SpudBannerSet.new
    respond_with @banner_set
  end

  def create
    @banner_set = SpudBannerSet.new(banner_set_params)
    if @banner_set.save
      flash.now[:notice] = 'Banner Set created successfully'
      render 'create'
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    respond_with @banner_set
  end

  def update
    if @banner_set.update(banner_set_params)
      flash.now[:notice] = 'Banner Set updated successfully'
      render 'create'
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    flash.now[:notice] = 'Banner Set deleted successfully' if @banner_set.destroy
    head :ok
  end

  private

  def load_record
    @banner_set = SpudBannerSet.find_by!(id: params[:id])
  end

  def banner_set_params
    params.require(:spud_banner_set).permit(:cropped, :height, :name, :short_name, :width, :has_rich_text)
  end

end

app/helpers/admin/banner_sets_helper.rb
module Admin::BannerSetsHelper
end

app/views/admin/banner_sets/_banner_set.html.erb
<%= content_tag :tr, :class => 'admin-banner-sets-list-item', 'data-id' => banner_set.id  do %>
  <td><%= banner_set.name %></td>
  <td class="table-actions">
    <%= link_to 'Manage Banners', admin_banner_set_path(banner_set), :class => 'btn btn-default btn-sm' %>
    <%= link_to 'Edit Configuration', edit_admin_banner_set_path(banner_set), :class => 'btn btn-default btn-sm admin-banner-set-edit' %>
    <%= link_to 'Delete', admin_banner_set_path(banner_set), :class => 'btn btn-default btn-sm btn-danger admin-banner-set-delete' %>
  </td>
  </span>
<% end %>

app/views/admin/banner_sets/_form.html.erb
<%= form_for @banner_set, :url => path, :html => {:class => 'form-horizontal admin-banner-set-form'} do |f| %>

  <%= tb_form_errors(f.object) %>

  <fieldset>
    <div class="form-group">
      <%= f.label :name, "Name",:class => "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= f.text_field :name, :class=>'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :width, "Width", :class => "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= f.text_field :width, :class=>'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :height, "Height", :class => "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= f.text_field :height, :class=>'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :cropped, "Cropped", :class => "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= f.check_box :cropped %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :has_rich_text, "Allow Rich Text", :class => "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= f.check_box :has_rich_text %>
      </div>
    </div>
  </fieldset>

<% end %>

app/views/admin/banner_sets/create.html.erb
<%= render :partial => 'banner_set', :locals => {:banner_set => @banner_set} %>

app/views/admin/banner_sets/edit.html.erb
<%= render :partial => 'form', :locals => {:path => admin_banner_set_path(@banner_set)} %>

app/views/admin/banner_sets/index.html.erb
<% content_for :data_controls do %>
  <%= link_to "New Banner Set", new_admin_banner_set_path, :class => "btn btn-primary spud_banner_sets_add_new", :title => "New Banner Set" %>
<% end %>

<% content_for :detail do %>
  <div class="table-responsive">
    <table class="table table-striped table-hover admin-banner-sets-list">
      <%= render :partial => 'banner_set', :collection => @banner_sets %>
    </table>
  </div>
  <script>
    $(document).ready(tb.banner_sets.init);
  </script>
<% end %>

app/views/admin/banner_sets/new.html.erb
<%= render :partial => 'form', :locals => {:path => admin_banner_sets_path} %>

app/views/admin/banner_sets/show.html.erb
<% content_for :data_controls do %>
  <%= link_to 'Upload Banner', new_admin_banner_set_banner_path(@banner_set), :class => 'btn btn-primary admin-banner-set-item-add' %>
<% end %>

<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>&nbsp</th>
        <th>Banner</th>
        <th>Start Date</th>
        <th>End Date</th>
        <% if !@banner_set.has_rich_text %>
          <th>Links to</th>
        <% end %>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody class="admin-banner-set-items-container">
      <%= render :partial => 'admin/banners/banner', :collection => @banner_set.banners %>
    </tbody>
  </table>
</div>

<script>
  $(document).ready(tb.banners.init);
</script>